# Inspired by https://blog.frankel.ch/github-actions-maven-releases/ (kudos)

name: Create Release Tag

on:
#  push: 
#    branches: [ release ]
  workflow_dispatch:
        

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # creates a settings.xml element accordingly
        
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Create Release Tag
      run: mvn -B release:prepare release:clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
